image: node:8.10

stages:
  - setup environment
  - build
  - deploy to dev servers

build & push image:
  stage: setup environment
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  variables:
    DOCKER_TLS_CERTDIR: ""
    CONTAINER_NAME: "$CI_REGISTRY/satoshilabs/trezor/connect/base"
  image: docker
  services:
    - docker:dind
  script:
    - docker pull $CONTAINER_NAME:latest || true
    - docker build --tag $CONTAINER_NAME:$CI_COMMIT_SHA --tag $CONTAINER_NAME:latest ./ci/docker/base
    - docker push $CONTAINER_NAME:$CI_COMMIT_SHA
    - docker push $CONTAINER_NAME:latest

build:
  stage: build
  script:
    - npm install -g yarn
    - yarn
    - yarn flow
    - yarn eslint
    - yarn test:unit
    - make build-connect
  artifacts:
    expire_in: 1 week
    paths:
      - build

deploy review:
  stage: deploy to dev servers
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  environment:
    name: $CI_BUILD_REF_NAME
    url: $BASE_REVIEW_URL/$CI_BUILD_REF_NAME
  script:
    - echo "Deploy a review app"
    - '[ -z "${DEPLOY_BASE_DIR}" ] && echo "Deploy base dir cannot be empty" && exit 255'
    - env
    - mkdir -p "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}"
    - echo "Copy dev build to web server ${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}..."
    - rsync --delete -va build/ "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}/"
  only:
    - branches
  tags:
    - deploy
